"""Add analytics indexes

Revision ID: 037083c922cb
Revises: 5c3fecea0533
Create Date: 2026-02-19 18:54:11.549449

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '037083c922cb'
down_revision: Union[str, Sequence[str], None] = '5c3fecea0533'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    try:
        op.create_index('idx_contact_zoho_stats', 'contact', ['workspace_id', 'zoho_last_synced_at'], unique=False)
    except Exception:
        pass
    try:
        op.create_index('idx_exec_stats', 'executioninstance', ['workspace_id', 'created_at', 'status'], unique=False)
    except Exception:
        pass
    try:
        op.create_index('idx_msg_stats', 'message', ['workspace_id', 'created_at', 'direction', 'delivery_status'], unique=False)
    except Exception:
        pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_msg_stats', table_name='message')
    op.drop_index('idx_exec_stats', table_name='executioninstance')
    op.drop_index('idx_contact_zoho_stats', table_name='contact')
    # ### end Alembic commands ###
