"""mission_7_1_abort_semantics

Revision ID: 1bd4be479c00
Revises: 602899cf266d
Create Date: 2026-02-19 14:53:01.136162

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '1bd4be479c00'
down_revision: Union[str, Sequence[str], None] = '602899cf266d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    try:
        with op.batch_alter_table('executioninstance', schema=None) as batch_op:
            batch_op.add_column(sa.Column('abort_reason', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    except Exception:
        pass
        
    try:
        with op.batch_alter_table('executioninstance', schema=None) as batch_op:
            batch_op.add_column(sa.Column('aborted_at', sa.DateTime(), nullable=True))
    except Exception:
        pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    try:
        with op.batch_alter_table('executioninstance', schema=None) as batch_op:
            batch_op.drop_column('aborted_at')
            batch_op.drop_column('abort_reason')
    except Exception:
        pass
    # ### end Alembic commands ###
