"""initial_schema_with_m6

Revision ID: 408346e0ab60
Revises: 
Create Date: 2026-02-19 14:03:30.982220

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '408346e0ab60'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('hashed_password', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('full_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('auth_provider', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('provider_subject', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_id'), 'user', ['id'], unique=False)
    op.create_index(op.f('ix_user_provider_subject'), 'user', ['provider_subject'], unique=False)
    op.create_table('workspace',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('subscription_tier', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workspace_id'), 'workspace', ['id'], unique=False)
    op.create_index(op.f('ix_workspace_name'), 'workspace', ['name'], unique=False)
    op.create_table('contact',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('external_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('first_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('last_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('additional_metadata', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspace.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contact_external_id'), 'contact', ['external_id'], unique=False)
    op.create_index(op.f('ix_contact_id'), 'contact', ['id'], unique=False)
    op.create_index(op.f('ix_contact_workspace_id'), 'contact', ['workspace_id'], unique=False)
    op.create_table('flow',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'PUBLISHED', name='flowstatus'), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspace.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_flow_id'), 'flow', ['id'], unique=False)
    op.create_index(op.f('ix_flow_name'), 'flow', ['name'], unique=False)
    op.create_index(op.f('ix_flow_workspace_id'), 'flow', ['workspace_id'], unique=False)
    op.create_table('integration',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('provider', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sa.Enum('CONNECTED', 'DISCONNECTED', 'ERROR', name='integrationstatus'), nullable=False),
    sa.Column('encrypted_config', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('connected_at', sa.DateTime(), nullable=True),
    sa.Column('last_checked_at', sa.DateTime(), nullable=True),
    sa.Column('last_error', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('provider_workspace_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspace.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'provider_workspace_id')
    )
    op.create_index(op.f('ix_integration_id'), 'integration', ['id'], unique=False)
    op.create_index(op.f('ix_integration_provider'), 'integration', ['provider'], unique=False)
    op.create_index(op.f('ix_integration_provider_workspace_id'), 'integration', ['provider_workspace_id'], unique=False)
    op.create_index(op.f('ix_integration_workspace_id'), 'integration', ['workspace_id'], unique=False)
    op.create_table('invite',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('token', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('accepted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspace.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_invite_id'), 'invite', ['id'], unique=False)
    op.create_index(op.f('ix_invite_token'), 'invite', ['token'], unique=True)
    op.create_table('passwordresettoken',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('token_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('used_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_passwordresettoken_id'), 'passwordresettoken', ['id'], unique=False)
    op.create_index(op.f('ix_passwordresettoken_token_hash'), 'passwordresettoken', ['token_hash'], unique=False)
    op.create_index(op.f('ix_passwordresettoken_user_id'), 'passwordresettoken', ['user_id'], unique=False)
    op.create_table('promptconfig',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('current_version_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspace.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_promptconfig_id'), 'promptconfig', ['id'], unique=False)
    op.create_index(op.f('ix_promptconfig_name'), 'promptconfig', ['name'], unique=False)
    op.create_index(op.f('ix_promptconfig_workspace_id'), 'promptconfig', ['workspace_id'], unique=False)
    op.create_table('webhookeventlog',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('workspace_id', sa.Uuid(), nullable=True),
    sa.Column('provider', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('provider_event_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sa.Enum('RECEIVED', 'QUEUED', 'PROCESSED', 'FAILED', name='webhookstatus'), nullable=False),
    sa.Column('correlation_id', sa.Uuid(), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('last_error', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('processed_at', sa.DateTime(), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspace.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'provider_event_id')
    )
    op.create_index(op.f('ix_webhookeventlog_id'), 'webhookeventlog', ['id'], unique=False)
    op.create_index(op.f('ix_webhookeventlog_workspace_id'), 'webhookeventlog', ['workspace_id'], unique=False)
    op.create_table('workspaceknowledgefile',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('filename', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('mime_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('storage_path', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('extracted_text', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspace.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workspaceknowledgefile_filename'), 'workspaceknowledgefile', ['filename'], unique=False)
    op.create_index(op.f('ix_workspaceknowledgefile_id'), 'workspaceknowledgefile', ['id'], unique=False)
    op.create_index(op.f('ix_workspaceknowledgefile_workspace_id'), 'workspaceknowledgefile', ['workspace_id'], unique=False)
    op.create_table('workspacemember',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('role', sa.Enum('OWNER', 'MEMBER', 'VIEWER', name='workspacerole'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspace.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'workspace_id')
    )
    op.create_table('channelidentity',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('contact_id', sa.Uuid(), nullable=False),
    sa.Column('provider', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('provider_user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['contact_id'], ['contact.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_channelidentity_id'), 'channelidentity', ['id'], unique=False)
    op.create_table('conversation',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('contact_id', sa.Uuid(), nullable=False),
    sa.Column('last_message_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['contact_id'], ['contact.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspace.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conversation_id'), 'conversation', ['id'], unique=False)
    op.create_index(op.f('ix_conversation_workspace_id'), 'conversation', ['workspace_id'], unique=False)
    op.create_table('flownode',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('flow_id', sa.Uuid(), nullable=False),
    sa.Column('type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('config', sa.JSON(), nullable=True),
    sa.Column('position_x', sa.Float(), nullable=False),
    sa.Column('position_y', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['flow_id'], ['flow.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_flownode_id'), 'flownode', ['id'], unique=False)
    op.create_table('flowversion',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('flow_id', sa.Uuid(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('definition_json', sa.JSON(), nullable=True),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['flow_id'], ['flow.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_flowversion_id'), 'flowversion', ['id'], unique=False)
    op.create_table('promptversion',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('prompt_config_id', sa.Uuid(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('business_profile_json', sa.JSON(), nullable=True),
    sa.Column('system_prompt_text', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('guardrails_json', sa.JSON(), nullable=True),
    sa.Column('structured_data', sa.JSON(), nullable=True),
    sa.Column('compiled_system_instruction', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('model', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('temperature', sa.Float(), nullable=False),
    sa.Column('max_tokens_per_execution', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['prompt_config_id'], ['promptconfig.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_promptversion_id'), 'promptversion', ['id'], unique=False)
    op.create_table('executioninstance',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('flow_version_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('RUNNING', 'COMPLETED', 'FAILED', 'WAITING', name='executionstatus'), nullable=False),
    sa.Column('current_node_id', sa.Uuid(), nullable=True),
    sa.Column('next_run_at', sa.DateTime(), nullable=True),
    sa.Column('contact_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['contact_id'], ['contact.id'], ),
    sa.ForeignKeyConstraint(['flow_version_id'], ['flowversion.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspace.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_executioninstance_id'), 'executioninstance', ['id'], unique=False)
    op.create_index(op.f('ix_executioninstance_workspace_id'), 'executioninstance', ['workspace_id'], unique=False)
    op.create_table('flowedge',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('flow_id', sa.Uuid(), nullable=False),
    sa.Column('source_node_id', sa.Uuid(), nullable=False),
    sa.Column('target_node_id', sa.Uuid(), nullable=False),
    sa.Column('source_handle', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['flow_id'], ['flow.id'], ),
    sa.ForeignKeyConstraint(['source_node_id'], ['flownode.id'], ),
    sa.ForeignKeyConstraint(['target_node_id'], ['flownode.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_flowedge_id'), 'flowedge', ['id'], unique=False)
    op.create_table('message',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('conversation_id', sa.Uuid(), nullable=False),
    sa.Column('direction', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('content', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('platform', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('delivery_status', sa.Enum('PENDING', 'SENDING', 'SENT', 'FAILED', name='deliverystatus'), nullable=False),
    sa.Column('provider_message_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.Column('last_attempt_at', sa.DateTime(), nullable=True),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('last_error', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('idempotency_key', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('is_outbound_intent', sa.Boolean(), nullable=False),
    sa.Column('additional_metadata', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversation.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspace.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_message_delivery_status'), 'message', ['delivery_status'], unique=False)
    op.create_index(op.f('ix_message_direction'), 'message', ['direction'], unique=False)
    op.create_index(op.f('ix_message_id'), 'message', ['id'], unique=False)
    op.create_index(op.f('ix_message_idempotency_key'), 'message', ['idempotency_key'], unique=False)
    op.create_index(op.f('ix_message_platform'), 'message', ['platform'], unique=False)
    op.create_index(op.f('ix_message_provider_message_id'), 'message', ['provider_message_id'], unique=False)
    op.create_index(op.f('ix_message_workspace_id'), 'message', ['workspace_id'], unique=False)
    op.create_table('executionsteplog',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('execution_instance_id', sa.Uuid(), nullable=False),
    sa.Column('node_id', sa.Uuid(), nullable=False),
    sa.Column('input_data', sa.JSON(), nullable=True),
    sa.Column('output_data', sa.JSON(), nullable=True),
    sa.Column('error_message', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['execution_instance_id'], ['executioninstance.id'], ),
    sa.ForeignKeyConstraint(['node_id'], ['flownode.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_executionsteplog_id'), 'executionsteplog', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_executionsteplog_id'), table_name='executionsteplog')
    op.drop_table('executionsteplog')
    op.drop_index(op.f('ix_message_workspace_id'), table_name='message')
    op.drop_index(op.f('ix_message_provider_message_id'), table_name='message')
    op.drop_index(op.f('ix_message_platform'), table_name='message')
    op.drop_index(op.f('ix_message_idempotency_key'), table_name='message')
    op.drop_index(op.f('ix_message_id'), table_name='message')
    op.drop_index(op.f('ix_message_direction'), table_name='message')
    op.drop_index(op.f('ix_message_delivery_status'), table_name='message')
    op.drop_table('message')
    op.drop_index(op.f('ix_flowedge_id'), table_name='flowedge')
    op.drop_table('flowedge')
    op.drop_index(op.f('ix_executioninstance_workspace_id'), table_name='executioninstance')
    op.drop_index(op.f('ix_executioninstance_id'), table_name='executioninstance')
    op.drop_table('executioninstance')
    op.drop_index(op.f('ix_promptversion_id'), table_name='promptversion')
    op.drop_table('promptversion')
    op.drop_index(op.f('ix_flowversion_id'), table_name='flowversion')
    op.drop_table('flowversion')
    op.drop_index(op.f('ix_flownode_id'), table_name='flownode')
    op.drop_table('flownode')
    op.drop_index(op.f('ix_conversation_workspace_id'), table_name='conversation')
    op.drop_index(op.f('ix_conversation_id'), table_name='conversation')
    op.drop_table('conversation')
    op.drop_index(op.f('ix_channelidentity_id'), table_name='channelidentity')
    op.drop_table('channelidentity')
    op.drop_table('workspacemember')
    op.drop_index(op.f('ix_workspaceknowledgefile_workspace_id'), table_name='workspaceknowledgefile')
    op.drop_index(op.f('ix_workspaceknowledgefile_id'), table_name='workspaceknowledgefile')
    op.drop_index(op.f('ix_workspaceknowledgefile_filename'), table_name='workspaceknowledgefile')
    op.drop_table('workspaceknowledgefile')
    op.drop_index(op.f('ix_webhookeventlog_workspace_id'), table_name='webhookeventlog')
    op.drop_index(op.f('ix_webhookeventlog_id'), table_name='webhookeventlog')
    op.drop_table('webhookeventlog')
    op.drop_index(op.f('ix_promptconfig_workspace_id'), table_name='promptconfig')
    op.drop_index(op.f('ix_promptconfig_name'), table_name='promptconfig')
    op.drop_index(op.f('ix_promptconfig_id'), table_name='promptconfig')
    op.drop_table('promptconfig')
    op.drop_index(op.f('ix_passwordresettoken_user_id'), table_name='passwordresettoken')
    op.drop_index(op.f('ix_passwordresettoken_token_hash'), table_name='passwordresettoken')
    op.drop_index(op.f('ix_passwordresettoken_id'), table_name='passwordresettoken')
    op.drop_table('passwordresettoken')
    op.drop_index(op.f('ix_invite_token'), table_name='invite')
    op.drop_index(op.f('ix_invite_id'), table_name='invite')
    op.drop_table('invite')
    op.drop_index(op.f('ix_integration_workspace_id'), table_name='integration')
    op.drop_index(op.f('ix_integration_provider_workspace_id'), table_name='integration')
    op.drop_index(op.f('ix_integration_provider'), table_name='integration')
    op.drop_index(op.f('ix_integration_id'), table_name='integration')
    op.drop_table('integration')
    op.drop_index(op.f('ix_flow_workspace_id'), table_name='flow')
    op.drop_index(op.f('ix_flow_name'), table_name='flow')
    op.drop_index(op.f('ix_flow_id'), table_name='flow')
    op.drop_table('flow')
    op.drop_index(op.f('ix_contact_workspace_id'), table_name='contact')
    op.drop_index(op.f('ix_contact_id'), table_name='contact')
    op.drop_index(op.f('ix_contact_external_id'), table_name='contact')
    op.drop_table('contact')
    op.drop_index(op.f('ix_workspace_name'), table_name='workspace')
    op.drop_index(op.f('ix_workspace_id'), table_name='workspace')
    op.drop_table('workspace')
    op.drop_index(op.f('ix_user_provider_subject'), table_name='user')
    op.drop_index(op.f('ix_user_id'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
