"""mission_8_zoho_lead_sync

Revision ID: 4b1048284463
Revises: 1bd4be479c00
Create Date: 2026-02-19 15:01:12.858140

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '4b1048284463'
down_revision: Union[str, Sequence[str], None] = '1bd4be479c00'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('zoholeadmapping',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('module_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('dedupe_strategy', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('field_mappings', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspace.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_zoholeadmapping_id'), 'zoholeadmapping', ['id'], unique=False)
    op.create_index(op.f('ix_zoholeadmapping_workspace_id'), 'zoholeadmapping', ['workspace_id'], unique=False)
    op.add_column('contact', sa.Column('zoho_lead_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('contact', sa.Column('zoho_last_synced_at', sa.DateTime(), nullable=True))
    op.create_index('idx_contact_workspace_zoho', 'contact', ['workspace_id', 'zoho_lead_id'], unique=False)
    op.create_index(op.f('ix_contact_zoho_lead_id'), 'contact', ['zoho_lead_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_contact_zoho_lead_id'), table_name='contact')
    op.drop_index('idx_contact_workspace_zoho', table_name='contact')
    op.drop_column('contact', 'zoho_last_synced_at')
    op.drop_column('contact', 'zoho_lead_id')
    op.drop_index(op.f('ix_zoholeadmapping_workspace_id'), table_name='zoholeadmapping')
    op.drop_index(op.f('ix_zoholeadmapping_id'), table_name='zoholeadmapping')
    op.drop_table('zoholeadmapping')
    # ### end Alembic commands ###
