"""module_foundation_and_audit

Revision ID: d820eb9ff19c
Revises: d33a49d45bce
Create Date: 2026-02-23 00:36:00.048349

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'd820eb9ff19c'
down_revision: Union[str, Sequence[str], None] = 'd33a49d45bce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('adminauditlog',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('actor_user_id', sa.Uuid(), nullable=False),
    sa.Column('action', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('entity_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('entity_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('workspace_id', sa.Uuid(), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('correlation_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['actor_user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspace.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_audit_actor_created', 'adminauditlog', ['actor_user_id', 'created_at'], unique=False)
    op.create_index('idx_audit_created', 'adminauditlog', ['created_at'], unique=False)
    op.create_index('idx_audit_entity_created', 'adminauditlog', ['entity_type', 'entity_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_adminauditlog_action'), 'adminauditlog', ['action'], unique=False)
    op.create_index(op.f('ix_adminauditlog_actor_user_id'), 'adminauditlog', ['actor_user_id'], unique=False)
    op.create_index(op.f('ix_adminauditlog_entity_id'), 'adminauditlog', ['entity_id'], unique=False)
    op.create_index(op.f('ix_adminauditlog_entity_type'), 'adminauditlog', ['entity_type'], unique=False)
    op.create_index(op.f('ix_adminauditlog_id'), 'adminauditlog', ['id'], unique=False)

    op.drop_table('systemmoduleconfig')
    op.create_table('systemmoduleconfig',
        sa.Column('id', sa.Uuid(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.Column('module_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('is_enabled', sa.Boolean(), nullable=False, server_default=sa.text('1')),
        sa.Column('config_json', sa.JSON(), nullable=True),
        sa.Column('updated_by_user_id', sa.Uuid(), nullable=True),
        sa.ForeignKeyConstraint(['updated_by_user_id'], ['user.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_systemmoduleconfig_module_name'), 'systemmoduleconfig', ['module_name'], unique=True)
    op.create_index(op.f('ix_systemmoduleconfig_id'), 'systemmoduleconfig', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('systemmoduleconfig')
    op.create_table('systemmoduleconfig',
        sa.Column('id', sa.Uuid(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.Column('module_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column('enabled', sa.Boolean(), nullable=False, server_default=sa.text('1')),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_systemmoduleconfig_module_name'), 'systemmoduleconfig', ['module_name'], unique=True)
    op.create_index(op.f('ix_systemmoduleconfig_id'), 'systemmoduleconfig', ['id'], unique=False)

    op.drop_index(op.f('ix_adminauditlog_id'), table_name='adminauditlog')
    op.drop_index(op.f('ix_adminauditlog_entity_type'), table_name='adminauditlog')
    op.drop_index(op.f('ix_adminauditlog_entity_id'), table_name='adminauditlog')
    op.drop_index(op.f('ix_adminauditlog_actor_user_id'), table_name='adminauditlog')
    op.drop_index(op.f('ix_adminauditlog_action'), table_name='adminauditlog')
    op.drop_index('idx_audit_entity_created', table_name='adminauditlog')
    op.drop_index('idx_audit_created', table_name='adminauditlog')
    op.drop_index('idx_audit_actor_created', table_name='adminauditlog')
    op.drop_table('adminauditlog')
    # ### end Alembic commands ###
